// export const POINTER_CONTEXT_DEFAULT = 0;
export const POINTER_CONTEXT_BODY = 0;
export const POINTER_CONTEXT_HEADER = -1;
export const POINTER_CONTEXT_SCROLLBAR_HANDLE = -2;
export const POINTER_CONTEXT_SCROLLBAR_LOWER = -3;
export const POINTER_CONTEXT_SCROLLBAR_HIGHER = -4;
export const POINTER_CONTEXT_SCROLLBAR_OTHER = -5;
export const POINTER_CONTEXT_SCROLLBAR_DEFAULT = -6;
